image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

stages:
  - build
  - test
  - push

build:
  stage: build
  script:
    - docker build -t $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHA .

test:
  stage: test
  script:
    - docker run $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHA ./mvnw test

push:
  stage: push
  script:
    - docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker tag $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHA $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
    - docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
  only:
    - main
